name: Python Test

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest ./tests --alluredir=./allure-results --disable-warnings  # исправлен путь
        continue-on-error: true

      - name: Archive allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 3

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/checkout@v4  # добавлен checkout
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz && sudo tar -xvzf allure-2.29.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Download allure results
        uses: actions/download-artifact@v4
        with:  # добавлены параметры
          name: allure-results
          path: allure-results
      - run: allure generate -c allure-results -o _site
      - name: Store report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 3

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish report
    steps:
      - name: Download site report
        uses: actions/download-artifact@v4
        with:  # добавлены параметры
          name: _site
          path: _site
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:  # добавлен path
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "https://evgsilkin.github.io/dm_api_tests/"